In [1]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import matplotlib as mat
import os
import datetime
import time
from tqdm import tqdm

# mat.rcParams['font.family'] = 'SimHei'
# mat.rcParams['font.sans-serif'] = 'SimHei'

#忽略警告
import warnings
warnings.filterwarnings('ignore')

# Data Reading

In [9]:
import os
import pandas as pd
from tqdm import tqdm

base_path = r"D:\TangYe\HBTPST\wifi_track_data\dacang\origin_data"
file_list = ['0706', '0707', '0708', '0709', '0710', '0711', '0712', '0714', '0715', '0718']

df_list = []

for i in tqdm(file_list):
    file_path = os.path.join(base_path, f"prob2022{i}.json")

    if os.path.exists(file_path):
        df = pd.read_json(file_path, lines=True)
        df_list.append(df)
    else:
        print(f"File not found: {file_path}")

df_read = pd.concat(df_list, ignore_index=True)

100%|██████████| 10/10 [00:05<00:00,  1.77it/s]

In [10]:
# convert time format
df = df_read.copy()

def Convert2Time(t):
    newT = time.localtime(t)
    timeStyle = time.strftime("%Y-%m-%d %H:%M:%S",newT)
    return timeStyle

df['t'] = df['t'].apply(Convert2Time)

#change 2021 -> 2022 (little data bug)
df['t'] = df['t'].apply(lambda t : t.replace('2021','2022'))

#drop _id column
df = df.drop('_id',axis=1)
df

                                     m    a    r                    t
0               [1, 128, 194, 0, 0, 0]  121  169  2022-07-05 23:57:16
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
4           [51, 51, 255, 86, 69, 185]  121  159  2022-07-05 23:57:20
...                                ...  ...  ...                  ...
1783997    [152, 34, 239, 8, 233, 105]   22  162  2022-07-18 16:06:29
1783998  [132, 65, 103, 218, 221, 212]   22  160  2022-07-18 16:06:29
1783999    [26, 204, 220, 147, 204, 1]   22  162  2022-07-18 16:06:29
1784000       [76, 2, 32, 111, 66, 59]   22  166  2022-07-18 16:06:29
1784001    [72, 81, 197, 94, 156, 205]   22  175  2022-07-18 16:06:29

[1784002 rows x 4 columns]

# Data Cleaning

### wash macs with unusual length

In [11]:
df = df[df.m.apply(lambda x : True if len(x) == 6 else False)]
df

                                     m    a    r                    t
0               [1, 128, 194, 0, 0, 0]  121  169  2022-07-05 23:57:16
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
4           [51, 51, 255, 86, 69, 185]  121  159  2022-07-05 23:57:20
...                                ...  ...  ...                  ...
1783997    [152, 34, 239, 8, 233, 105]   22  162  2022-07-18 16:06:29
1783998  [132, 65, 103, 218, 221, 212]   22  160  2022-07-18 16:06:29
1783999    [26, 204, 220, 147, 204, 1]   22  162  2022-07-18 16:06:29
1784000       [76, 2, 32, 111, 66, 59]   22  166  2022-07-18 16:06:29
1784001    [72, 81, 197, 94, 156, 205]   22  175  2022-07-18 16:06:29

[1778823 rows x 4 columns]

### wash macs that contains 0

In [12]:
df = df[df.m.apply(lambda x : False if 0 in x else True)]
df

                                     m    a    r                    t
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
4           [51, 51, 255, 86, 69, 185]  121  159  2022-07-05 23:57:20
5          [80, 2, 145, 187, 143, 221]  121  164  2022-07-05 23:57:20
...                                ...  ...  ...                  ...
1783997    [152, 34, 239, 8, 233, 105]   22  162  2022-07-18 16:06:29
1783998  [132, 65, 103, 218, 221, 212]   22  160  2022-07-18 16:06:29
1783999    [26, 204, 220, 147, 204, 1]   22  162  2022-07-18 16:06:29
1784000       [76, 2, 32, 111, 66, 59]   22  166  2022-07-18 16:06:29
1784001    [72, 81, 197, 94, 156, 205]   22  175  2022-07-18 16:06:29

[1304025 rows x 4 columns]

### wash fake macs

#### 清除多播mac地址和广播mac地址

**单播地址（unicast address**）表示单一设备、节点；

**多播地址或者组播地址（multicast address 、 group address）** 表示一组设备、节点；

**广播地址（broadcast address）** 是组播的特例，表示所有地址，全用F表示：FF:FF:FF:FF:FF:FF。


如MAC地址：54-BF-64-2B-09-50，第1个字节是54，第2个字节是BF …，而十六进制54写成二进制为：01010100，红色位标识代表的组播地址与单播地址区分位，单播地址红色位一定为0，即MAC地址一的第一个字节一定是2的倍数.

In [13]:
df = df[df.m.apply(lambda x :True if x[0]%2 == 0 else False)]
df

                                     m    a    r                    t
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
5          [80, 2, 145, 187, 143, 221]  121  164  2022-07-05 23:57:20
7            [96, 238, 92, 49, 127, 3]  121  183  2022-07-05 23:57:33
...                                ...  ...  ...                  ...
1783997    [152, 34, 239, 8, 233, 105]   22  162  2022-07-18 16:06:29
1783998  [132, 65, 103, 218, 221, 212]   22  160  2022-07-18 16:06:29
1783999    [26, 204, 220, 147, 204, 1]   22  162  2022-07-18 16:06:29
1784000       [76, 2, 32, 111, 66, 59]   22  166  2022-07-18 16:06:29
1784001    [72, 81, 197, 94, 156, 205]   22  175  2022-07-18 16:06:29

[1203150 rows x 4 columns]

根据IEEE 802 MAC地址的定义，若MAC地址第一个字节的从低位开始的第二个bit为1，则表示该MAC地址类型为本地管理类型，本地管理类型MAC地址不保证是全局唯一的。随机MAC一般选用本地管理类型的MAC地址。

In [14]:
def IsFakeMac(x):
    x = format(x[0],'04b')
    n = len(x) - 2
    if x[n] == '1':
        return True
    else:
        return False
    
df = df[~df.m.apply(IsFakeMac)]
df

                                     m    a    r                    t
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
5          [80, 2, 145, 187, 143, 221]  121  164  2022-07-05 23:57:20
7            [96, 238, 92, 49, 127, 3]  121  183  2022-07-05 23:57:33
...                                ...  ...  ...                  ...
1783995   [20, 178, 229, 137, 47, 142]   22  161  2022-07-18 16:06:16
1783997    [152, 34, 239, 8, 233, 105]   22  162  2022-07-18 16:06:29
1783998  [132, 65, 103, 218, 221, 212]   22  160  2022-07-18 16:06:29
1784000       [76, 2, 32, 111, 66, 59]   22  166  2022-07-18 16:06:29
1784001    [72, 81, 197, 94, 156, 205]   22  175  2022-07-18 16:06:29

[773631 rows x 4 columns]

### Convert Mac to String

In [15]:
def convertMac2Str(x):
    list_s = map(str,x)
    s = ','.join(list_s)
    return s

df['m'] = df['m'].apply(convertMac2Str)
df.head()

                      m    a    r                    t
1  80,2,145,187,143,221  121  159  2022-07-05 23:57:16
2  176,89,71,72,233,219  121  160  2022-07-05 23:57:16
3  160,65,71,44,196,200  121  163  2022-07-05 23:57:16
5  80,2,145,187,143,221  121  164  2022-07-05 23:57:20
7    96,238,92,49,127,3  121  183  2022-07-05 23:57:33

In [16]:
df = df.reindex(columns = ['a','r','t','m'])
df.head()

     a    r                    t                     m
1  121  159  2022-07-05 23:57:16  80,2,145,187,143,221
2  121  160  2022-07-05 23:57:16  176,89,71,72,233,219
3  121  163  2022-07-05 23:57:16  160,65,71,44,196,200
5  121  164  2022-07-05 23:57:20  80,2,145,187,143,221
7  121  183  2022-07-05 23:57:33    96,238,92,49,127,3

### wash macs that only appeared once

In [17]:
df = df[df.duplicated("m",keep = False)]
df

           a    r                    t                       m
1        121  159  2022-07-05 23:57:16    80,2,145,187,143,221
2        121  160  2022-07-05 23:57:16    176,89,71,72,233,219
3        121  163  2022-07-05 23:57:16    160,65,71,44,196,200
5        121  164  2022-07-05 23:57:20    80,2,145,187,143,221
7        121  183  2022-07-05 23:57:33      96,238,92,49,127,3
...      ...  ...                  ...                     ...
1783995   22  161  2022-07-18 16:06:16   20,178,229,137,47,142
1783997   22  162  2022-07-18 16:06:29    152,34,239,8,233,105
1783998   22  160  2022-07-18 16:06:29  132,65,103,218,221,212
1784000   22  166  2022-07-18 16:06:29       76,2,32,111,66,59
1784001   22  175  2022-07-18 16:06:29    72,81,197,94,156,205

[748025 rows x 4 columns]

### wash macs that only appeared in one place

In [18]:
list_count = df.groupby(['m']).a.value_counts()
dd = list_count.to_frame().rename(columns={'a':'A'}).reset_index()
mac_Once = dd[~dd.duplicated('m', keep=False)].m.reset_index().drop('index',axis=1)
mac_Once

                           m
0     100,145,170,114,172,60
1      100,161,50,219,105,98
2     100,162,252,107,240,89
3     100,164,208,151,254,40
4     100,164,252,107,240,89
...                      ...
2899   96,98,173,154,151,204
2900      96,98,173,86,34,94
2901      96,98,175,32,50,51
2902      96,98,175,86,34,94
2903     96,98,177,1,128,194

[2904 rows x 1 columns]

In [19]:
#删除mac_Once对应的mac地址
df = df.loc[~df.m.isin(mac_Once.m)]
df

          a    r                    t                        m
12605    22  171  2022-07-05 23:49:36      48,74,38,155,214,98
12606    22  163  2022-07-05 23:49:36    252,107,240,89,142,53
12607    22  170  2022-07-05 23:49:36  164,125,159,153,152,106
12615    22  166  2022-07-05 23:49:47    252,107,240,89,142,53
12616    22  170  2022-07-05 23:49:47  164,125,159,153,152,106
...      ..  ...                  ...                      ...
1783995  22  161  2022-07-18 16:06:16    20,178,229,137,47,142
1783997  22  162  2022-07-18 16:06:29     152,34,239,8,233,105
1783998  22  160  2022-07-18 16:06:29   132,65,103,218,221,212
1784000  22  166  2022-07-18 16:06:29        76,2,32,111,66,59
1784001  22  175  2022-07-18 16:06:29     72,81,197,94,156,205

[727100 rows x 4 columns]

### Convert RSSI

In [20]:
df.r = df.loc[:,'r'].apply(lambda x : format(x,'04b'))

def bin2dec(b):
    number = 0
    counter = 0
    for i in b[::-1]: 
        number += int(i)*(2**counter)
        counter += 1

    return number

def Rssi2dec(r):
    n = bin2dec(r[1:8])
    if r[0] == '0':
        return n
    else:
        return -n
    
df.r = df.r.apply(Rssi2dec)
df

          a   r                    t                        m
12605    22 -43  2022-07-05 23:49:36      48,74,38,155,214,98
12606    22 -35  2022-07-05 23:49:36    252,107,240,89,142,53
12607    22 -42  2022-07-05 23:49:36  164,125,159,153,152,106
12615    22 -38  2022-07-05 23:49:47    252,107,240,89,142,53
12616    22 -42  2022-07-05 23:49:47  164,125,159,153,152,106
...      ..  ..                  ...                      ...
1783995  22 -33  2022-07-18 16:06:16    20,178,229,137,47,142
1783997  22 -34  2022-07-18 16:06:29     152,34,239,8,233,105
1783998  22 -32  2022-07-18 16:06:29   132,65,103,218,221,212
1784000  22 -38  2022-07-18 16:06:29        76,2,32,111,66,59
1784001  22 -47  2022-07-18 16:06:29     72,81,197,94,156,205

[727100 rows x 4 columns]

In [22]:
df.to_csv('../wifi_track_data/dacang/track_data/dacang_track_data_0925.csv', index=False)