In [1]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import matplotlib as mat
import os
import datetime
import time
from tqdm import tqdm

# mat.rcParams['font.family'] = 'SimHei'
# mat.rcParams['font.sans-serif'] = 'SimHei'

#忽略警告
import warnings
warnings.filterwarnings('ignore')

# Data Reading

In [2]:
import os
import glob
import pandas as pd
from tqdm import tqdm


def _origin_data_dir():
    for rel in (
        os.path.join("wifi_track_data", "dacang", "origin_data"),
        os.path.join("..", "wifi_track_data", "dacang", "origin_data"),
    ):
        p = os.path.normpath(os.path.join(os.getcwd(), rel))
        if os.path.isdir(p):
            return p
    raise FileNotFoundError(
        "找不到 origin_data，请在项目根目录或 data_clean 目录下运行本单元"
    )


base_path = _origin_data_dir()
file_paths = sorted(glob.glob(os.path.join(base_path, "prob2022*.json")))
if not file_paths:
    raise FileNotFoundError(f"{base_path} 下没有 prob2022*.json")

df_list = []
for file_path in tqdm(file_paths):
    df = pd.read_json(file_path, lines=True)
    df_list.append(df)

df_read = pd.concat(df_list, ignore_index=True)

100%|██████████| 28/28 [00:33<00:00,  1.19s/it]

In [3]:
# convert time format
df = df_read.copy()

def Convert2Time(t):
    newT = time.localtime(t)
    timeStyle = time.strftime("%Y-%m-%d %H:%M:%S",newT)
    return timeStyle

df['t'] = df['t'].apply(Convert2Time)

#change 2021 -> 2022 (little data bug)
df['t'] = df['t'].apply(lambda t : t.replace('2021','2022'))

#drop _id column
df = df.drop('_id',axis=1)
df

                                     m    a    r                    t
0               [1, 128, 194, 0, 0, 0]  121  169  2022-07-05 23:57:16
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
4           [51, 51, 255, 86, 69, 185]  121  159  2022-07-05 23:57:20
...                                ...  ...  ...                  ...
5039701  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:48:38
5039702  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:51:14
5039703      [1, 0, 94, 127, 255, 250]   66  161  2022-08-07 23:51:14
5039704      [1, 0, 94, 127, 255, 250]   66  162  2022-08-07 23:54:42
5039705  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:54:42

[5039706 rows x 4 columns]

# Data Cleaning

### wash macs with unusual length

In [4]:
df = df[df.m.apply(lambda x : True if len(x) == 6 else False)]
df

                                     m    a    r                    t
0               [1, 128, 194, 0, 0, 0]  121  169  2022-07-05 23:57:16
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
4           [51, 51, 255, 86, 69, 185]  121  159  2022-07-05 23:57:20
...                                ...  ...  ...                  ...
5039701  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:48:38
5039702  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:51:14
5039703      [1, 0, 94, 127, 255, 250]   66  161  2022-08-07 23:51:14
5039704      [1, 0, 94, 127, 255, 250]   66  162  2022-08-07 23:54:42
5039705  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:54:42

[5023707 rows x 4 columns]

### wash macs that contains 0

In [5]:
df = df[df.m.apply(lambda x : False if 0 in x else True)]
df

                                     m    a    r                    t
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
4           [51, 51, 255, 86, 69, 185]  121  159  2022-07-05 23:57:20
5          [80, 2, 145, 187, 143, 221]  121  164  2022-07-05 23:57:20
...                                ...  ...  ...                  ...
5039697  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:44:30
5039698  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:46:54
5039701  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:48:38
5039702  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:51:14
5039705  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:54:42

[3666204 rows x 4 columns]

### wash fake macs

#### 清除多播mac地址和广播mac地址

**单播地址（unicast address**）表示单一设备、节点；

**多播地址或者组播地址（multicast address 、 group address）** 表示一组设备、节点；

**广播地址（broadcast address）** 是组播的特例，表示所有地址，全用F表示：FF:FF:FF:FF:FF:FF。


如MAC地址：54-BF-64-2B-09-50，第1个字节是54，第2个字节是BF …，而十六进制54写成二进制为：01010100，红色位标识代表的组播地址与单播地址区分位，单播地址红色位一定为0，即MAC地址一的第一个字节一定是2的倍数.

In [6]:
df = df[df.m.apply(lambda x :True if x[0]%2 == 0 else False)]
df

                                     m    a    r                    t
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
5          [80, 2, 145, 187, 143, 221]  121  164  2022-07-05 23:57:20
7            [96, 238, 92, 49, 127, 3]  121  183  2022-07-05 23:57:33
...                                ...  ...  ...                  ...
5039697  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:44:30
5039698  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:46:54
5039701  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:48:38
5039702  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:51:14
5039705  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:54:42

[3352008 rows x 4 columns]

根据IEEE 802 MAC地址的定义，若MAC地址第一个字节的从低位开始的第二个bit为1，则表示该MAC地址类型为本地管理类型，本地管理类型MAC地址不保证是全局唯一的。随机MAC一般选用本地管理类型的MAC地址。

In [7]:
def IsFakeMac(x):
    x = format(x[0],'04b')
    n = len(x) - 2
    if x[n] == '1':
        return True
    else:
        return False
    
df = df[~df.m.apply(IsFakeMac)]
df

                                     m    a    r                    t
1          [80, 2, 145, 187, 143, 221]  121  159  2022-07-05 23:57:16
2          [176, 89, 71, 72, 233, 219]  121  160  2022-07-05 23:57:16
3          [160, 65, 71, 44, 196, 200]  121  163  2022-07-05 23:57:16
5          [80, 2, 145, 187, 143, 221]  121  164  2022-07-05 23:57:20
7            [96, 238, 92, 49, 127, 3]  121  183  2022-07-05 23:57:33
...                                ...  ...  ...                  ...
5039697  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:44:30
5039698  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:46:54
5039701  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:48:38
5039702  [88, 102, 186, 101, 140, 144]   66  177  2022-08-07 23:51:14
5039705  [88, 102, 186, 101, 140, 144]   66  176  2022-08-07 23:54:42

[2060822 rows x 4 columns]

### Convert Mac to String

In [8]:
def convertMac2Str(x):
    list_s = map(str,x)
    s = ','.join(list_s)
    return s

df['m'] = df['m'].apply(convertMac2Str)
df.head()

                      m    a    r                    t
1  80,2,145,187,143,221  121  159  2022-07-05 23:57:16
2  176,89,71,72,233,219  121  160  2022-07-05 23:57:16
3  160,65,71,44,196,200  121  163  2022-07-05 23:57:16
5  80,2,145,187,143,221  121  164  2022-07-05 23:57:20
7    96,238,92,49,127,3  121  183  2022-07-05 23:57:33

In [9]:
df = df.reindex(columns = ['a','r','t','m'])
df.head()

     a    r                    t                     m
1  121  159  2022-07-05 23:57:16  80,2,145,187,143,221
2  121  160  2022-07-05 23:57:16  176,89,71,72,233,219
3  121  163  2022-07-05 23:57:16  160,65,71,44,196,200
5  121  164  2022-07-05 23:57:20  80,2,145,187,143,221
7  121  183  2022-07-05 23:57:33    96,238,92,49,127,3

### wash macs that only appeared once

In [10]:
df = df[df.duplicated("m",keep = False)]
df

           a    r                    t                       m
1        121  159  2022-07-05 23:57:16    80,2,145,187,143,221
2        121  160  2022-07-05 23:57:16    176,89,71,72,233,219
3        121  163  2022-07-05 23:57:16    160,65,71,44,196,200
5        121  164  2022-07-05 23:57:20    80,2,145,187,143,221
7        121  183  2022-07-05 23:57:33      96,238,92,49,127,3
...      ...  ...                  ...                     ...
5039697   66  177  2022-08-07 23:44:30  88,102,186,101,140,144
5039698   66  177  2022-08-07 23:46:54  88,102,186,101,140,144
5039701   66  176  2022-08-07 23:48:38  88,102,186,101,140,144
5039702   66  177  2022-08-07 23:51:14  88,102,186,101,140,144
5039705   66  176  2022-08-07 23:54:42  88,102,186,101,140,144

[1991974 rows x 4 columns]

### wash macs that only appeared in one place

In [11]:
list_count = df.groupby(['m']).a.value_counts()
dd = list_count.to_frame().rename(columns={'a':'A'}).reset_index()
mac_Once = dd[~dd.duplicated('m', keep=False)].m.reset_index().drop('index',axis=1)
mac_Once

                           m
0     100,145,159,224,55,191
1      100,145,159,48,148,53
2     100,145,162,146,189,25
3     100,145,163,172,115,82
4      100,145,163,48,148,53
...                      ...
8211   96,98,173,154,151,204
8212      96,98,173,86,34,94
8213      96,98,175,32,50,51
8214      96,98,175,86,34,94
8215     96,98,177,1,128,194

[8216 rows x 1 columns]

In [12]:
#删除mac_Once对应的mac地址
df = df.loc[~df.m.isin(mac_Once.m)]
df

          a    r                    t                        m
12605    22  171  2022-07-05 23:49:36      48,74,38,155,214,98
12606    22  163  2022-07-05 23:49:36    252,107,240,89,142,53
12607    22  170  2022-07-05 23:49:36  164,125,159,153,152,106
12615    22  166  2022-07-05 23:49:47    252,107,240,89,142,53
12616    22  170  2022-07-05 23:49:47  164,125,159,153,152,106
...      ..  ...                  ...                      ...
5039697  66  177  2022-08-07 23:44:30   88,102,186,101,140,144
5039698  66  177  2022-08-07 23:46:54   88,102,186,101,140,144
5039701  66  176  2022-08-07 23:48:38   88,102,186,101,140,144
5039702  66  177  2022-08-07 23:51:14   88,102,186,101,140,144
5039705  66  176  2022-08-07 23:54:42   88,102,186,101,140,144

[1940387 rows x 4 columns]

### Convert RSSI

In [13]:
df.r = df.loc[:,'r'].apply(lambda x : format(x,'04b'))

def bin2dec(b):
    number = 0
    counter = 0
    for i in b[::-1]: 
        number += int(i)*(2**counter)
        counter += 1

    return number

def Rssi2dec(r):
    n = bin2dec(r[1:8])
    if r[0] == '0':
        return n
    else:
        return -n
    
df.r = df.r.apply(Rssi2dec)
df

          a   r                    t                        m
12605    22 -43  2022-07-05 23:49:36      48,74,38,155,214,98
12606    22 -35  2022-07-05 23:49:36    252,107,240,89,142,53
12607    22 -42  2022-07-05 23:49:36  164,125,159,153,152,106
12615    22 -38  2022-07-05 23:49:47    252,107,240,89,142,53
12616    22 -42  2022-07-05 23:49:47  164,125,159,153,152,106
...      ..  ..                  ...                      ...
5039697  66 -49  2022-08-07 23:44:30   88,102,186,101,140,144
5039698  66 -49  2022-08-07 23:46:54   88,102,186,101,140,144
5039701  66 -48  2022-08-07 23:48:38   88,102,186,101,140,144
5039702  66 -49  2022-08-07 23:51:14   88,102,186,101,140,144
5039705  66 -48  2022-08-07 23:54:42   88,102,186,101,140,144

[1940387 rows x 4 columns]

In [14]:
df.to_csv('../wifi_track_data/dacang/track_data/dacang_track_data_0508.csv', index=False)