# Track Cluster

In [3]:
import pandas as pd
import numpy as np
from utils_tool import utils
from utils_tool import myplot
df = pd.read_csv(r'..\wifi_track_data\dacang\track_data\dacang_track_data_final.csv')
df.t = pd.to_datetime(df.t)
mac_list = df.m.unique()
df_wifipos = pd.read_csv(r'..\wifi_track_data\dacang\pos_data\wifi_pos.csv')
from tqdm import tqdm
from importlib import reload
from grid_world.experts import Experts

import warnings
warnings.filterwarnings('ignore')

%load_ext autoreload
%autoreload 2

no background image

## feature clustering

In [10]:
#获取专家轨迹
experts = Experts(40,30,trajs_file_path = r"..\wifi_track_data\dacang\learned_trajs\learned_trajs_0921.csv")
_,x,y = experts.GetExpertsMovingCenter()

Get experts trajs num:7353
trajs all avg length: 22

In [12]:
mac_list = df['m'].unique()
ori_mac_list = df.oriMac.unique()
ori_Mac = []
data_count = []
Dur = []
trajs_len = []
wifi_count = []
active_moment = []
middle_moment = []
moving_dis = []
center_x = []
center_y = []

traj_idx = 0

for m in mac_list:
    ori_Mac.append(m.split('-')[1])
    df_now = utils.GetDfNow(df, m)
    data_count.append(len(df_now))
    t1 = df_now.iloc[0].t
    t2 = df_now.iloc[len(df_now)-1].t
    t1 = t1.hour + t1.minute/60 + t1.second/3600
    t2 = t2.hour + t2.minute/60 + t2.second/3600
    Dur.append(t2-t1)
    middle_moment.append((t2+t1)/2)
    wifi_count.append(len(df_now['a'].unique()))
    trajs_len.append(len(df_now))
    h = 0
    row_last = df_now.iloc[0]
    dis = 0
    for i,row in df_now.iterrows():
        h += row.t.hour + row.t.minute/60 + row.t.second/3600
        if row.a != row_last.a:
            dis += utils.GetWifiTrackDistance(row.a,row_last.a,df_wifipos)
        row_last = row
    active_moment.append(h/len(df_now))
    moving_dis.append(dis)
    current_traj_len = len(df_now)
    # 计算轨迹中心点坐标
    if current_traj_len > 0:
        start_idx = traj_idx
        end_idx = traj_idx + current_traj_len
        center_x.append(np.mean(x[start_idx:end_idx]))
        center_y.append(np.mean(y[start_idx:end_idx]))
        # 更新轨迹索引
        traj_idx = end_idx
    else:
        center_x.append(0)
        center_y.append(0)


print(f"mac_list length: {len(mac_list)}")
print(f"ori_Mac length: {len(ori_Mac)}")
print(f"data_count length: {len(data_count)}")
print(f"Dur length: {len(Dur)}")
print(f"experts.traj_all_lens length: {len(trajs_len)}")
print(f"wifi_count length: {len(wifi_count)}")
print(f"active_moment length: {len(active_moment)}")
print(f"moving_dis length: {len(moving_dis)}")
print(f"middle_moment length: {len(middle_moment)}")
print(f"x length: {len(center_x)}")
print(f"y length: {len(center_y)}")

df_sta = pd.DataFrame({'mac':mac_list,
                       'ori_mac':ori_Mac,
                       'data_count':data_count,#数据量
                       'Dur':Dur,#持续时间
                       'trajs_len':trajs_len,#轨迹长度
                       'wifi_count':wifi_count,#经过的wifi数量
                       'active_moment':active_moment,#活跃时间
                       'moving_dis':moving_dis,#移动距离
                       'middle_moment':middle_moment,#中间时刻
                        'center_x':center_x,
                        'center_y':center_y
                       })
df_sta

AttributeError: 'DataFrame' object has no attribute 'oriMac'

In [9]:
myplot.Boxes([(df_sta.data_count,"数据量"),
              (df_sta.active_moment,"平均活跃时刻"),
              (df_sta.moving_dis,"移动距离"),
              (df_sta.middle_moment,"中间时刻"),
              (df_sta.Dur,'持续时间')
              ])

## Clearing outliers

In [38]:
#归一化
parse_list = ['data_count',
              'active_moment',
              'moving_dis',
              'middle_moment',
              'Dur'
              ]
df_outlier = df_sta[parse_list]
df_outlier = utils.Normalize_df(df_outlier,parse_list,mul_index=10)
df_outlier

      data_count  active_moment  moving_dis  middle_moment       Dur
0       0.140845       9.132320    0.485928       8.488534  2.971261
1       0.422535       9.391764    0.664276       8.489134  2.972419
2       0.633803      10.000000    0.000000      10.000000  0.051526
3       2.887324       1.726939    0.149592       4.849477  9.999884
4       0.563380       4.335655    0.000000       4.848877  9.998726
...          ...            ...         ...            ...       ...
1338    0.774648       6.346865    3.009432       6.479083  6.752003
1339    2.042254       7.007901    4.082751       7.096587  5.561577
1340    0.211268       7.669503    0.000000       6.504150  3.746353
1341    0.492958       7.745633    0.732842       6.525739  3.413807
1342    1.760563       7.748544    0.216981       7.943053  2.262633

[1343 rows x 5 columns]

In [39]:
cols = {'data_count':'数据量','active_moment':'平均活跃时刻','moving_dis':'移动距离','middle_moment':'中间时刻','Dur':'持续时间'}
df_outlier = df_outlier.rename(columns=cols)
df_outlier

           数据量     平均活跃时刻      移动距离       中间时刻      持续时间
0     0.140845   9.132320  0.485928   8.488534  2.971261
1     0.422535   9.391764  0.664276   8.489134  2.972419
2     0.633803  10.000000  0.000000  10.000000  0.051526
3     2.887324   1.726939  0.149592   4.849477  9.999884
4     0.563380   4.335655  0.000000   4.848877  9.998726
...        ...        ...       ...        ...       ...
1338  0.774648   6.346865  3.009432   6.479083  6.752003
1339  2.042254   7.007901  4.082751   7.096587  5.561577
1340  0.211268   7.669503  0.000000   6.504150  3.746353
1341  0.492958   7.745633  0.732842   6.525739  3.413807
1342  1.760563   7.748544  0.216981   7.943053  2.262633

[1343 rows x 5 columns]

In [40]:
parse_list = ['数据量','平均活跃时刻','移动距离','中间时刻','持续时间']

In [41]:
from sklearn.ensemble import IsolationForest
rng = np.random.RandomState(42)
model_IF = IsolationForest(max_samples=2000,random_state=rng,contamination='auto')
model_IF.fit(df_outlier)
df_outlier['label'] = model_IF.predict(df_outlier[parse_list])
print(df_outlier.label.value_counts())

myplot.Scatter_Matrix(df_outlier,
                      dimentions = parse_list,
                        color = 'label')

label
 1    1199
-1     144
Name: count, dtype: int64

In [42]:
parse_list = ['data_count',
              'active_moment',
              'moving_dis',
              'middle_moment',
              'Dur'
              ]
df_cluster = df_sta[['mac']+parse_list][df_outlier.label == 1].reset_index(drop=True)
parse_list = ['数据量','平均活跃时刻','移动距离','中间时刻','持续时间']
df_cluster = df_cluster.rename(columns=cols)
df_cluster = utils.Normalize_df(df_cluster,parse_list,mul_index=10)

df_cluster

,mac,数据量,平均活跃时刻,移动距离,中间时刻,持续时间
0,"7.6-48,74,38,155,214,98",4.315789,0.463112,0.312675,4.550973,9.999884
1,"7.6-32,50,51,210,96,61",0.842105,3.852679,0.000000,4.550152,9.998721
2,"7.6-48,74,38,133,29,213",1.263158,3.214097,0.000000,4.550152,9.998721
3,"7.6-20,178,229,137,47,142",0.315789,4.134817,0.000000,4.549577,9.997675
4,"7.6-4,207,140,11,128,186",0.736842,2.844352,0.000000,4.551219,9.994885
...,...,...,...,...,...,...
1194,"8.7-76,2,32,111,66,59",0.315789,5.505951,0.843023,4.907632,4.120485
1195,"8.7-252,4,28,35,119,153",1.157895,6.465890,6.290260,6.783089,6.738976
1196,"8.7-56,251,20,50,26,70",0.315789,8.184425,0.000000,6.817424,3.721271
1197,"8.7-144,173,247,200,14,93",0.736842,8.283342,1.531774,6.846995,3.387391
1198,"8.7-176,70,146,156,89,69",2.631579,8.287125,0.453530,8.788329,2.231600

In [43]:
myplot.Scatter_Matrix(df_cluster,
                      dimentions = parse_list)

## Simple categorization of residents, tourists, and passersby ##
- Considered a resident when the number of days in the village exceeds 15 days
- When the number of days spent in the area for more than 10 hours in a day exceeds 5 days, they are considered residents.
- When the number of days spent in the area for less than 0.5 hours in a day exceeds 5 days, they are considered as passersby
- When staying in the area for more than 10 hours in a day for more than 5 days, you are considered a long-stay visitor.
- The rest are considered short-term visitors

In [44]:
def DivideId(df_now):
    days = df_now.calender.unique()
    count = 0
    isPassing = 0
    for i in range(len(days)):
        df_one = df_now[df_now.calender == days[i]]
        time = df_one.iloc[len(df_one)-1].t - df_one.iloc[0].t
        h = time.components.hours
        if h>10:
            count += 1
        elif h<0.5:
            isPassing += 1
    if len(days) > 15:
        return 'resident'
    if isPassing > 5:
        return 'pass'
    elif count < 5 and count>0:
        return 'tourist_long'
    elif count == 0:
        return 'tourist_short'
    else:
        return 'resident'
    

tourist_long_list = []
tourist_short_list = []
resident_list = []
pass_list = []

for mac in tqdm(ori_mac_list,desc="Dividing:"):
    df_now = df[df.oriMac == mac]
    df_now.sort_values(by='t')
    result = DivideId(df_now)
    if result == 'pass':
        pass_list.append(mac)
    elif result == 'tourist_long':
        tourist_long_list.append(mac)
    elif result == 'tourist_short':
        tourist_short_list.append(mac)
    else:
        resident_list.append(mac)

# add id to df_sta
def GetId(m):
    if m in tourist_long_list:
        return 1
    elif m in tourist_short_list:
        return 2
    elif m in resident_list:
        return 0
    else:
        return -1
df_sta['id'] = df_sta.ori_mac.apply(GetId)
df_cluster['id'] = df_sta.ori_mac.apply(GetId)

print('pass count:',len(pass_list))
print('long tourists count:',len(tourist_long_list))
print('short tourists count:',len(tourist_short_list))
print('residents count:',len(resident_list))

Dividing:: 100%|██████████| 315/315 [00:00<00:00, 576.96it/s]

pass count: 0
long tourists count: 142
short tourists count: 108
residents count: 65

In [45]:
myplot.Scatter_Matrix(df_cluster,
                      dimentions = parse_list,
                        color = 'id',
                        color_scale='Jet')

## K-means++

In [46]:
# residents receiving optimal clustering
df_score_resi = utils.GetKmeansClusterNumDf(df_cluster,parse_list)
myplot.Double_Axes_Line(df_score_resi,"n_clusters","calinski","silhouette","聚类数","卡林斯基-哈拉巴斯指数","轮廓系数")

In [51]:
df_cluster['cluster'] = utils.Kmeans(df_cluster,parse_list,4)
myplot.Scatter_Matrix(df_cluster,
                      dimentions = parse_list,
                        color = 'cluster',
                        color_scale='Jet')
df_cluster.cluster.value_counts()

cluster
0    585
2    230
3    209
1    175
Name: count, dtype: int64

In [52]:
df_cluster

,mac,数据量,平均活跃时刻,移动距离,中间时刻,持续时间,id,cluster
0,"7.6-48,74,38,155,214,98",4.315789,0.463112,0.312675,4.550973,9.999884,0,0
1,"7.6-32,50,51,210,96,61",0.842105,3.852679,0.000000,4.550152,9.998721,0,0
2,"7.6-48,74,38,133,29,213",1.263158,3.214097,0.000000,4.550152,9.998721,0,0
3,"7.6-20,178,229,137,47,142",0.315789,4.134817,0.000000,4.549577,9.997675,0,0
4,"7.6-4,207,140,11,128,186",0.736842,2.844352,0.000000,4.551219,9.994885,0,0
...,...,...,...,...,...,...,...,...
1194,"8.7-76,2,32,111,66,59",0.315789,5.505951,0.843023,4.907632,4.120485,0,2
1195,"8.7-252,4,28,35,119,153",1.157895,6.465890,6.290260,6.783089,6.738976,2,3
1196,"8.7-56,251,20,50,26,70",0.315789,8.184425,0.000000,6.817424,3.721271,0,2
1197,"8.7-144,173,247,200,14,93",0.736842,8.283342,1.531774,6.846995,3.387391,1,2
1198,"8.7-176,70,146,156,89,69",2.631579,8.287125,0.453530,8.788329,2.231600,0,2

In [53]:
#将聚类结果加入到df
cluster = []
for i,r in df.iterrows():
    if r.m in df_cluster.mac.values:
        cluster.append(df_cluster[df_cluster.mac == r.m].cluster.values[0])
    else:
        cluster.append(-1)
df['cluster'] = cluster

In [55]:
df.to_csv(r'..\wifi_track_data\dacang\track_data\dacang_track_data_clustered.csv',index=False)

In [63]:
df_cluster_result = df_cluster[['mac','cluster']]
df_cluster_result.to_csv(r'..\wifi_track_data\dacang\cluster_data\cluster_result.csv',index=False)

## Residents, tourists clustered separately

In [57]:
#获得居民最佳聚类数
df_resident = df_cluster[df_cluster.id == 0]
df_score_resi = utils.GetKmeansClusterNumDf(df_resident,parse_list)
myplot.Double_Axes_Line(df_score_resi,"n_clusters","calinski","silhouette","聚类数","卡林斯基-哈拉巴斯指数","轮廓系数")

In [58]:
#获得游客最佳聚类数
df_tourist = df_cluster[df_cluster.id == 1]
df_score_tour = utils.GetKmeansClusterNumDf(df_tourist,parse_list)
myplot.Double_Axes_Line(df_score_tour,"n_clusters","calinski","silhouette","聚类数","卡林斯基-哈拉巴斯指数","轮廓系数")

In [59]:
df_resident['cluster'] = utils.Kmeans(df_resident,parse_list,4)
myplot.Scatter_Matrix(df_resident,
                      dimentions = parse_list,
                        color = 'cluster',
                        color_scale='Jet')

In [60]:
df_tourist['cluster'] = utils.Kmeans(df_tourist,parse_list,3)
myplot.Scatter_Matrix(df_tourist,
                      dimentions = parse_list,
                        color = 'cluster',
                        color_scale='Jet')

In [62]:
df_resident.to_csv(r"..\wifi_track_data\dacang\cluster_data\dacang_track_data_resident.csv",index=False)
df_tourist.to_csv(r"..\wifi_track_data\dacang\cluster_data\dacang_track_data_tourist.csv",index=False)